name: CI
 on:
  push:
  branches:
  - 
main
  pull_request:
  branches:
  - 
main
 .github/workflows/ci.yml⽂件，配置GitHub Actions进⾏持续集成：
jobs:
  build:
  runs-on: ubuntu-latest
  steps:
  - 
name: Checkout code
  uses: actions/checkout@v2
  - 
name: Set up JDK 11
  uses: actions/setup-java@v2
  with:
  java-version: '11'
  - 
name: Build with Gradle
  run: ./gradlew build
